# Generated by Django 4.0.3 on 2022-03-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_course_timeperiod_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeperiod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
