# Generated by Django 4.0.3 on 2022-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_timeperiod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
